
version: 2
updates:
  # BouncyCastle
  - package-ecosystem: "nuget"
    directory: "/Libraries/BouncyCastle"
    schedule:
      interval: "daily"

  # MailKit
  - package-ecosystem: "nuget"
    directory: "/Libraries/MailKit"
    schedule:
      interval: "daily"

  # MimeKit
  - package-ecosystem: "nuget"
    directory: "/Libraries/MimeKit"
    schedule:
      interval: "daily"
