

version: 2
updates:

  #mailkit
  - package-ecosystem: "nuget"
    directory: "/Libraries/MailKit"
    schedule:
      interval: "weekly"

  #mimekit
  - package-ecosystem: "nuget"
    directory: "/Libraries/MimeKit"
    schedule:
      interval: "weekly"


  #bouncycastle
  - package-ecosystem: "nuget"
    directory: "/Libraries/BouncyCastle"
    schedule:
      interval: "weekly"